FROM ubuntu:latest
   
# install base dependences    
RUN apt-get update && \
    apt-get install -y make cmake git curl build-essential m4 sudo gdbserver python3-pip \
    gdb libreadline-dev bison flex zlib1g-dev libicu-dev icu-devtools tmux zile zip \
    gawk wget python3-full python3-virtualenv graphviz python3-dev libpq-dev python3-psycopg2 libssl-dev

RUN deluser --remove-home ubuntu
# add postgres user and make data dir        
RUN groupadd -r postgres && useradd --no-log-init -r -m -s /bin/bash -g postgres -G sudo postgres

# make postgres a sudoer
RUN echo "postgres ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user && \
    chmod 0440 /etc/sudoers.d/user

USER postgres
    
ENV PGDATA /home/postgres/data
RUN /bin/rm -Rf "$PGDATA" && mkdir "$PGDATA"
WORKDIR "/home/postgres"

# get postgres source and compile with debug and no optimization
RUN git clone  https://github.com/michelp/postgres-upstream.git --depth=1 && \
    cd postgres-upstream && CFLAGS="-DTOAST_MAX_CHUNK_SIZE=8192" ./configure \
    --prefix=/usr/ \
    --without-icu \
    --enable-debug \
    --enable-depend --enable-cassert --enable-profiling \
    CFLAGS="-ggdb -Og -g3 -fno-omit-frame-pointer" \
#    CFLAGS="-O3" \
    && make -j 4 && sudo make install

# COPY --chown=postgres:postgres postgres-upstream postgres-upstream
# RUN cd postgres-upstream && ./configure \
#     --prefix=/usr/ \
#     --with-python \
#     --with-openssl \
#     --without-icu \
#     --enable-debug \
# #    --enable-depend --enable-cassert --enable-profiling \
# #    CFLAGS="-ggdb -Og -g3 -fno-omit-frame-pointer" \
#     CFLAGS="-O3" \
#     && make -j 4 && sudo make install \
#     && cd contrib/postgres_fdw && make && sudo make install \
#     && cd .. && /bin/rm -Rf postgres-upstream

# get GraphBLAS, compile with debug symbols    
RUN curl -s -L -J https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/refs/tags/v10.0.2.tar.gz | \
    tar zxvf - && cd GraphBLAS-10.0.2 && \
    make library \
#    CMAKE_OPTIONS='-DCMAKE_BUILD_TYPE=Debug -DGRAPHBLAS_COMPACT=1' \
    && sudo make install \
    && /bin/rm -Rf GraphBLAS-10.0.2

RUN sudo ldconfig

# put test stuff into pg home        
RUN mkdir "/home/postgres/onesparse"
WORKDIR "/home/postgres/onesparse"
COPY . .
    
ENV EDITOR zile    

# make the extension
#RUN .virt/bin/python3 generate.py onesparse/onesparse--0.1.0.sql
RUN sudo make && sudo make install && sudo make clean

# start the database            
RUN initdb -D "$PGDATA" -c shared_preload_libraries='onesparse' -c search_path='public,onesparse' --encoding UTF8
EXPOSE 5432
# wait forever

CMD tail -f /dev/null
