site_name: OneSparse Postgres

nav:
  - Home: index.md
  - Examples: test_examples_header.md
  - Matrix: test_matrix_header.md
  - Vector: test_vector_header.md
  - Scalar: test_scalar_header.md
  - Semiring: test_semiring_header.md
  - Monoid: test_monoid_header.md
  - BinaryOp: test_binaryop_header.md
  - IndexUnaryOp: test_indexunaryop_header.md
  - UnaryOp: test_unaryop_header.md
  - Descriptor: test_descriptor_header.md
  - Type: test_type_header.md
  
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - C
    - python
    - pgsql
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    

extra_css:
  - stylesheets/extra.css

