site_name: OneSparse Postgres
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - C
    - python
    - pgsql

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    
