site_name: OneSparse

nav:
  - Intro: docs.md
  - Docker Demo: docker.md
  - Algorithms: test_examples_header.md
  - Matrix: test_matrix_header.md
  - Vector: test_vector_header.md
  - Scalar: test_scalar_header.md
  - Semiring: test_semiring_header.md
  - Monoid: test_monoid_header.md
  - BinaryOp: test_binaryop_header.md
  - IndexUnaryOp: test_indexunaryop_header.md
  - UnaryOp: test_unaryop_header.md
  - Descriptor: test_descriptor_header.md
  - Type: test_type_header.md

use_directory_urls: false

extra:
  static_dir: landing_page

theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
  highlightjs: true
  hljs_languages:
    - C
    - python
    - pgsql
    - toc:
        toc_depth: 2     # how many levels deep to include
        permalink: true  # adds a link icon next to each heading
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
