set client_min_messages = 'WARNING';
create extension if not exists onesparse;
set search_path = 'onesparse';
select ({type.max}::{type.pgtype})::scalar + {type.min}::{type.pgtype};
select {type.max}::{type.pgtype} + ({type.min}::{type.pgtype})::scalar;
select ({type.max}::{type.pgtype})::scalar - {type.max}::{type.pgtype};
select {type.max}::{type.pgtype} - ({type.max}::{type.pgtype})::scalar;
select ({type.max}::{type.pgtype})::scalar * {type.min}::{type.pgtype};
select {type.max}::{type.pgtype} * ({type.min}::{type.pgtype})::scalar;
select ({type.max}::{type.pgtype})::scalar / {type.max}::{type.pgtype};
select {type.max}::{type.pgtype} / ({type.max}::{type.pgtype})::scalar;
