#include "pggraphblas.h"
PG_MODULE_MAGIC;

pgGrB_Semiring semirings[960];

#include "type.c"
#include "isequal.c"
#include "vector.c"
#include "matrix.c"

void
_PG_init(void)
{
  GrB_Info info;
  info = GrB_init (GrB_BLOCKING);
  if (! (info == GrB_SUCCESS || info == GrB_NO_VALUE))
    {
      elog(ERROR, "%s", GrB_error());
      return;
    }

  SEMIRING_GROUP(0, FIRST_);
  SEMIRING_GROUP(40, SECOND_);
  SEMIRING_GROUP(80, MIN_);
  SEMIRING_GROUP(120, MAX_);
  SEMIRING_GROUP(160, PLUS_);
  SEMIRING_GROUP(200, MINUS_);
  SEMIRING_GROUP(240, TIMES_);
  SEMIRING_GROUP(280, DIV_);
  SEMIRING_GROUP(320, ISEQ_);
  SEMIRING_GROUP(360, ISNE_);
  SEMIRING_GROUP(400, ISGT_);
  SEMIRING_GROUP(440, ISLT_);
  SEMIRING_GROUP(480, ISGE_);
  SEMIRING_GROUP(520, ISLE_);
  SEMIRING_GROUP(560, LOR_);
  SEMIRING_GROUP(600, LAND_);
  SEMIRING_GROUP(640, LXOR_);
  SEMIRING_BOOL_GROUP(680, EQ_);
  SEMIRING_BOOL_GROUP(720, NE_);
  SEMIRING_BOOL_GROUP(760, GT_);
  SEMIRING_BOOL_GROUP(800, LT_);
  SEMIRING_BOOL_GROUP(840, GE_);
  SEMIRING_BOOL_GROUP(880, LE_);
  SEMIRING_PURE_BOOL_GROUP(920);
}
