\pset linestyle unicode
\pset border 2
-- # Descriptor

-- Descriptors control specific details of GraphBLAS operations.
--
-- | OneSparse Name | SuiteSparse Name |
-- |----------------|------------------|
-- | t1 | GrB_DESC_T1 |
-- | t0 | GrB_DESC_T0 |
-- | t0t1 | GrB_DESC_T0T1 |
-- | c | GrB_DESC_C |
-- | ct1 | GrB_DESC_CT1 |
-- | ct0 | GrB_DESC_CT0 |
-- | ct0t1 | GrB_DESC_CT0T1 |
-- | s | GrB_DESC_S |
-- | st1 | GrB_DESC_ST1 |
-- | st0 | GrB_DESC_ST0 |
-- | st0t1 | GrB_DESC_ST0T1 |
-- | sc | GrB_DESC_SC |
-- | sct1 | GrB_DESC_SCT1 |
-- | sct0 | GrB_DESC_SCT0 |
-- | sct0t1 | GrB_DESC_SCT0T1 |
-- | r | GrB_DESC_R |
-- | rt1 | GrB_DESC_RT1 |
-- | rt0 | GrB_DESC_RT0 |
-- | rt0t1 | GrB_DESC_RT0T1 |
-- | rc | GrB_DESC_RC |
-- | rct1 | GrB_DESC_RCT1 |
-- | rct0 | GrB_DESC_RCT0 |
-- | rct0t1 | GrB_DESC_RCT0T1 |
-- | rs | GrB_DESC_RS |
-- | rst1 | GrB_DESC_RST1 |
-- | rst0 | GrB_DESC_RST0 |
-- | rst0t1 | GrB_DESC_RST0T1 |
-- | rsc | GrB_DESC_RSC |
-- | rsct1 | GrB_DESC_RSCT1 |
-- | rsct0 | GrB_DESC_RSCT0 |
-- | rsct0t1 | GrB_DESC_RSCT0T1 |
