name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          docker run -d -e POSTGRES_PASSWORD=password -it --name onesparse-test onesparse/onesparse:0.1.0
          sleep 5
          docker exec -u postgres -it onesparse-test make installcheck

